apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: nginx-taint
spec:
  selector:
    matchLabels:
      app: nginx-taint
  replicas: 3 
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nginx-taint
    spec:
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "lab"
        effect: "NoSchedule"
      containers:
      - name: nginx-taint
        image: nginx:1.7.9
        ports:
        - containerPort: 80
